name: Docker Build Push API

on:
  push:
    branches:
      - main
      - MATH-141

  pull_request:
    branches:
      - main

  workflow_dispatch:

#  schedule:
#    - cron: '0 0 * * 0'

jobs:
  mathematica:
    name: Mathematica
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Copy License File
        shell: bash
        run: |
          mkdir -p "./mathematica/Licensing"
          cd "./mathematica/Licensing"
          cat $WOLFRAM_LICENSE_FILE > mathpass
        env:
          WOLFRAM_LICENSE_FILE: ${{ secrets.WOLFRAM_LICENSE_FILE }}

      - name: Run WolframScript in Docker
        shell: pwsh
        run: |
          Set-Location "./mathematica"
          .\Run-Wolfram-Container.ps1