name: Docker Build Push API

on:
  push:
    branches:
      - main
      - MATH-141

  pull_request:
    branches:
      - main

  workflow_dispatch:

#  schedule:
#    - cron: '0 0 * * 0'

jobs:
  mathematica:
    name: Mathematica
    runs-on: windows-latest
    
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Copy License File
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "./mathematica/Licensing" -Force
          Set-Location "./mathematica/Licensing"
          $env:WOLFRAM_LICENSE_FILE | Out-File -FilePath "mathpass" -Encoding ascii
        env:
          WOLFRAM_LICENSE_FILE: ${{ secrets.WOLFRAM_LICENSE_FILE }}

      - name: Run WolframScript in Docker
        shell: pwsh
        run: |
          Set-Location "./mathematica"
          .\Run-Wolfram-Container.ps1